package com.ecotrack.data.model

/**
 * A personalised eco-tip generated by [com.ecotrack.ml.RecommendationEngine].
 *
 * @property title Short headline for the tip.
 * @property body  Detailed actionable advice.
 * @property saving Estimated weekly CO₂ saving in kg if the tip is followed.
 * @property category The activity category this tip relates to.
 */
data class Recommendation(
    val title: String,
    val body: String,
    val saving: Double,
    val category: ActivityType
)
